backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"
publish_mode: editorial_workflow

collections:
  - name: "images"
    label: "Images"
    folder: "public/images"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Alt Text", name: "alt", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }